### ISSUE TITLE
Make it less opinionated with background color so it follows the theme

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/dismiss#1]
First off, thanks - just saw your message on Zulip and tried it out.

I see that it sets a background color on the box which doesn't match that of Seven nor Basis for that matter.

![Screenshot from 2020-11-03 14-29-51](https://user-images.githubusercontent.com/1071483/98032044-66887c80-1de1-11eb-93f0-a3ecece81ba2.png)

Perhaps just make the background a semi-opaque grey so it will take a bit of the tint from the message color. And perhaps also remove some of the styling so it follows Seven/Basis flat style a bit closer. Other themes may want to override it anyway.

**Comment by ghost** [comment]
Fixed with the above commit.

![image](https://user-images.githubusercontent.com/2385329/102439142-d1300780-4071-11eb-8ac9-59c84e32391e.png)
