### ISSUE TITLE
Fewer options for where to place the script might be good

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/dismiss#2]
It seems odd to me that it has all these settings for where to place the script. I say just pick the best default and be done with it. I've never seen any other js add-on hedge its bets so.

If someone wants it differently perhaps they can port Advanced Aggregation. Or make it an option only for the settings file.

**Comment by ghost** [comment]
I kept it the same as the D7 module to start with, but I agree with you, and I like less code to maintain 😉 Fixed with the above commit.
